FROM nvidia/cuda:12.2.2-base-ubuntu22.04

ENV PYTHON_VERSION=3.11

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y update \
    && apt-get -y install --no-install-recommends \
    python${PYTHON_VERSION} \
    python3-pip \
    ffmpeg \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python3 && \
    ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python && \
    ln -s -f /usr/bin/pip3 /usr/bin/pip

WORKDIR /app

RUN pip install -U pip setuptools --no-cache-dir


COPY . .

# up-to-date versions 20240804 jan@panoch.net
#RUN pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 pyannote.audio==3.3.1 -i https://download.pytorch.org/whl/cu118 --no-cache-dir
RUN pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 -i https://download.pytorch.org/whl/cu118 --no-cache-dir
RUN pip install git+https://github.com/jan-panoch/whisperX.git --no-cache-dir


RUN pip install -r requirements.txt --no-cache-dir

EXPOSE 8000
ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1", "--timeout", "0", "app.main:app", "-k", "uvicorn.workers.UvicornWorker"]
