"""Initial schema

Revision ID: b66b17122860
Revises:
Create Date: 2025-10-25 17:58:01.437365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b66b17122860"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for each task (Primary Key)",
        ),
        sa.Column(
            "uuid",
            sa.String(),
            nullable=False,
            comment="Universally unique identifier for each task",
        ),
        sa.Column(
            "status", sa.String(), nullable=False, comment="Current status of the task"
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment="JSON data representing the result of the task",
        ),
        sa.Column(
            "file_name",
            sa.String(),
            nullable=True,
            comment="Name of the file associated with the task",
        ),
        sa.Column(
            "url",
            sa.String(),
            nullable=True,
            comment="URL of the file associated with the task",
        ),
        sa.Column(
            "audio_duration",
            sa.Float(),
            nullable=True,
            comment="Duration of the audio in seconds",
        ),
        sa.Column(
            "language",
            sa.String(),
            nullable=True,
            comment="Language of the file associated with the task",
        ),
        sa.Column(
            "task_type",
            sa.String(),
            nullable=False,
            comment="Type/category of the task",
        ),
        sa.Column(
            "task_params", sa.JSON(), nullable=True, comment="Parameters of the task"
        ),
        sa.Column(
            "duration",
            sa.Float(),
            nullable=True,
            comment="Duration of the task execution",
        ),
        sa.Column(
            "start_time",
            sa.DateTime(),
            nullable=True,
            comment="Start time of the task execution",
        ),
        sa.Column(
            "end_time",
            sa.DateTime(),
            nullable=True,
            comment="End time of the task execution",
        ),
        sa.Column(
            "error",
            sa.String(),
            nullable=True,
            comment="Error message, if any, associated with the task",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Date and time of creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Date and time of last update",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
