"""Add retry count to tasks.

Revision ID: f866cbfd2901
Revises: 6142b214f12d
Create Date: 2026-08-22 05:14:37.610035

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f866cbfd2901"
down_revision: str | None = "6142b214f12d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "retry_count",
                sa.Integer(),
                server_default="0",
                nullable=False,
                comment="Number of retry attempts made after a transient failure",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("retry_count")

    # ### end Alembic commands ###
