"""Initial schema.

Revision ID: 6142b214f12d
Revises:
Create Date: 2026-08-21 18:50:23.711562

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6142b214f12d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speaker_embeddings",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier (Primary Key)",
        ),
        sa.Column(
            "uuid",
            sa.String(),
            nullable=False,
            comment="Universally unique identifier for each speaker embedding",
        ),
        sa.Column(
            "task_uuid",
            sa.String(),
            nullable=True,
            comment="Optional link to the originating diarization task",
        ),
        sa.Column(
            "speaker_label",
            sa.String(),
            nullable=False,
            comment="User-facing name for the speaker",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Free-text description of the speaker",
        ),
        sa.Column(
            "embedding", sa.JSON(), nullable=False, comment="Speaker embedding vector"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Date and time of creation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    with op.batch_alter_table("speaker_embeddings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_speaker_embeddings_task_uuid"), ["task_uuid"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Unique identifier for each task (Primary Key)",
        ),
        sa.Column(
            "uuid",
            sa.String(),
            nullable=False,
            comment="Universally unique identifier for each task",
        ),
        sa.Column(
            "status", sa.String(), nullable=False, comment="Current status of the task"
        ),
        sa.Column(
            "result",
            sa.JSON(),
            nullable=True,
            comment="JSON data representing the result of the task",
        ),
        sa.Column(
            "file_name",
            sa.String(),
            nullable=True,
            comment="Name of the file associated with the task",
        ),
        sa.Column(
            "url",
            sa.String(),
            nullable=True,
            comment="URL of the file associated with the task",
        ),
        sa.Column(
            "callback_url",
            sa.String(),
            nullable=True,
            comment="Callback URL to POST results to",
        ),
        sa.Column(
            "audio_duration",
            sa.Float(),
            nullable=True,
            comment="Duration of the audio in seconds",
        ),
        sa.Column(
            "language",
            sa.String(),
            nullable=True,
            comment="Language of the file associated with the task",
        ),
        sa.Column(
            "task_type",
            sa.String(),
            nullable=False,
            comment="Type/category of the task",
        ),
        sa.Column(
            "task_params", sa.JSON(), nullable=True, comment="Parameters of the task"
        ),
        sa.Column(
            "duration",
            sa.Float(),
            nullable=True,
            comment="Duration of the task execution",
        ),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Start time of the task execution",
        ),
        sa.Column(
            "end_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="End time of the task execution",
        ),
        sa.Column(
            "error",
            sa.String(),
            nullable=True,
            comment="Error message, if any, associated with the task",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Date and time of creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Date and time of last update",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    with op.batch_alter_table("speaker_embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_speaker_embeddings_task_uuid"))

    op.drop_table("speaker_embeddings")
    # ### end Alembic commands ###
